### ISSUE TITLE
Question: AWS Grid emissions factors / renewable energy projects / Renewable Energy Credits

### ISSUE THREAD

**Issue by mikegchambers** [cloud-carbon-footprint/cloud-carbon-coefficients#13]
Hello.  Great work here. Thanks. 

To the best of my understanding, over the last few months Amazon has significantly increased it's portfolio of renewable energy projects.  These can be seen here: https://sustainability.aboutamazon.com/about/around-the-globe?energyType=true

In addition to this, AWS report that:
```
AWS purchases and retires environmental attributes, like Renewable Energy Credits 
and Guarantees of Origin, to cover the non-renewable energy we use in these regions:
    - U.S. West (Oregon)
    - GovCloud (U.S. West)
    - Europe (Frankfurt)
    - Canada (Central)
    - Europe (Ireland)
```
Src: https://sustainability.aboutamazon.com/environment/the-cloud?energyType=true

Given this, Is there a method (or would you seek a method) to combine this data into /data/grid-emissions-factors-aws.csv ?  

For example would there be an issue with setting the CO2e to zero for each of the regions listed above, and making reductions to other regions where Amazon has local renewable energy projects?

Thoughts?

**Comment by davidmytton** [comment]
Thanks for the question. Currently, [the grid factors are used based on public data for the local region](https://www.cloudcarbonfootprint.org/docs/methodology#carbon-estimates-co2e). RECs / REGOs have no impact on the carbon factor because they're market instruments, which is why the local emissions factors are used. Deploying new clean energy to the grid would reduce the overall grid emissions factor rather than zeroing the emissions for a specific cloud region (or DC).

I'm going to close this as it's not an issue with this repo, but if you'd like to discuss further please feel free to post in https://groups.google.com/g/cloud-carbon-footprint

**Comment by mikegchambers** [comment]
Thanks @davidmytton.  I have reported all this over to the Google Group, and hope to continue to the chat over there.
